### PR TITLE
- Redesigned home page to introduce Garage  2.0 project

### PR DESCRIPTION
**Pull request by CodeXito90**
- Added highlights and features description
- a button link to go to parking management

### CODE REVIEW

**Comment by SinonSoderlund** [comment]
you should probably update the program.cs routing to get the program to default to the landing page, also maybe update _layout to remove the home controller links and delete the home controller all together

**Comment by MohammadAbdulkader9** [comment]
yes, i think we can safely remove privacy link

**Comment by CodeXito90** [comment]
I got rid of the privacy link as mentioned, and changed the default routing to home/index instead of vehicle/index.

**Review by SinonSoderlund — APPROVED** [review]

**Review by MohammadAbdulkader9 — APPROVED** [review]

**Comment by MohammadAbdulkader9** [comment]
bra jobbat, nice introduction!

**Pull request merged**
